version: '3.7'
services:
  streaks_api:
    build: ./
    ports:
      - 4000:4000
    volumes:
      - streaks_data:/opt/data
    environment:
      - REQ_KEY=key
    restart: always

volumes:
  streaks_data: